/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PosRouteImport } from './routes/pos'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as InventoryIndexRouteImport } from './routes/inventory.index'
import { Route as InventoryProductIdRouteImport } from './routes/inventory.$productId'
import { Route as InventoryNewRouteImport } from './routes/inventory.new'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ShopProductIdRouteImport } from './routes/shop/$productId'
import { Route as AccountOrderOrderIdRouteImport } from './routes/account.order.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryProductIdRoute = InventoryProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryNewRoute = InventoryNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => InventoryRoute,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopProductIdRoute = ShopProductIdRouteImport.update({
  id: '/shop/$productId',
  path: '/shop/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrderOrderIdRoute = AccountOrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => AccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/advisor': typeof AdvisorRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/customers': typeof CustomersRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/manage': typeof ManageRoute
  '/orders': typeof OrdersRoute
  '/pos': typeof PosRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/inventory/$productId': typeof InventoryProductIdRoute
  '/inventory/new': typeof InventoryNewRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/account/': typeof AccountIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/account/order/$orderId': typeof AccountOrderOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/customers': typeof CustomersRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/manage': typeof ManageRoute
  '/orders': typeof OrdersRoute
  '/pos': typeof PosRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/inventory/$productId': typeof InventoryProductIdRoute
  '/inventory/new': typeof InventoryNewRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/account': typeof AccountIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/shop': typeof ShopIndexRoute
  '/account/order/$orderId': typeof AccountOrderOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/advisor': typeof AdvisorRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/customers': typeof CustomersRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/manage': typeof ManageRoute
  '/orders': typeof OrdersRoute
  '/pos': typeof PosRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/inventory/$productId': typeof InventoryProductIdRoute
  '/inventory/new': typeof InventoryNewRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/account/': typeof AccountIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/account/order/$orderId': typeof AccountOrderOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/advisor'
    | '/cart'
    | '/checkout'
    | '/customers'
    | '/inventory'
    | '/ledger'
    | '/login'
    | '/manage'
    | '/orders'
    | '/pos'
    | '/saved'
    | '/settings'
    | '/inventory/$productId'
    | '/inventory/new'
    | '/shop/$productId'
    | '/account/'
    | '/inventory/'
    | '/shop/'
    | '/account/order/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advisor'
    | '/cart'
    | '/checkout'
    | '/customers'
    | '/ledger'
    | '/login'
    | '/manage'
    | '/orders'
    | '/pos'
    | '/saved'
    | '/settings'
    | '/inventory/$productId'
    | '/inventory/new'
    | '/shop/$productId'
    | '/account'
    | '/inventory'
    | '/shop'
    | '/account/order/$orderId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/advisor'
    | '/cart'
    | '/checkout'
    | '/customers'
    | '/inventory'
    | '/ledger'
    | '/login'
    | '/manage'
    | '/orders'
    | '/pos'
    | '/saved'
    | '/settings'
    | '/inventory/$productId'
    | '/inventory/new'
    | '/shop/$productId'
    | '/account/'
    | '/inventory/'
    | '/shop/'
    | '/account/order/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdvisorRoute: typeof AdvisorRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CustomersRoute: typeof CustomersRoute
  InventoryRoute: typeof InventoryRouteWithChildren
  LedgerRoute: typeof LedgerRoute
  LoginRoute: typeof LoginRoute
  ManageRoute: typeof ManageRoute
  OrdersRoute: typeof OrdersRoute
  PosRoute: typeof PosRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  ShopProductIdRoute: typeof ShopProductIdRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/$productId': {
      id: '/inventory/$productId'
      path: '/$productId'
      fullPath: '/inventory/$productId'
      preLoaderRoute: typeof InventoryProductIdRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/new': {
      id: '/inventory/new'
      path: '/new'
      fullPath: '/inventory/new'
      preLoaderRoute: typeof InventoryNewRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$productId': {
      id: '/shop/$productId'
      path: '/shop/$productId'
      fullPath: '/shop/$productId'
      preLoaderRoute: typeof ShopProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/order/$orderId': {
      id: '/account/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/account/order/$orderId'
      preLoaderRoute: typeof AccountOrderOrderIdRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AccountRouteChildren {
  AccountIndexRoute: typeof AccountIndexRoute
  AccountOrderOrderIdRoute: typeof AccountOrderOrderIdRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountIndexRoute: AccountIndexRoute,
  AccountOrderOrderIdRoute: AccountOrderOrderIdRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface InventoryRouteChildren {
  InventoryProductIdRoute: typeof InventoryProductIdRoute
  InventoryNewRoute: typeof InventoryNewRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
}

const InventoryRouteChildren: InventoryRouteChildren = {
  InventoryProductIdRoute: InventoryProductIdRoute,
  InventoryNewRoute: InventoryNewRoute,
  InventoryIndexRoute: InventoryIndexRoute,
}

const InventoryRouteWithChildren = InventoryRoute._addFileChildren(
  InventoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AdvisorRoute: AdvisorRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CustomersRoute: CustomersRoute,
  InventoryRoute: InventoryRouteWithChildren,
  LedgerRoute: LedgerRoute,
  LoginRoute: LoginRoute,
  ManageRoute: ManageRoute,
  OrdersRoute: OrdersRoute,
  PosRoute: PosRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  ShopProductIdRoute: ShopProductIdRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
